name: beariscope_scouter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  path: ^1.9.0
  path_provider: ^2.1.5
  flutter_riverpod: ^3.0.0
  go_router: ^17.0.0
  riverpod_annotation: ^4.0.0
  http: ^1.6.0
  uuid: ^4.5.1
  meta: ^1.17.0
  flutter:
    sdk: flutter
  audioplayers: ^6.5.1
  cupertino_icons: ^1.0.8
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  loading_animation_widget: ^1.3.0
  auto_size_text: ^3.0.0
  syncfusion_flutter_sliders: ^32.1.21
  pressable_flutter: ^1.0.4
  libkoala:
    git:
      url: https://github.com/bear-metal-apps/libkoala.git
      ref: v3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner:
  riverpod_generator:
  hive_ce_generator: ^1.9.2

flutter:
  uses-material-design: true
  assets:
    - resources/ui_creator.json


