name: beariscope_scouter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
    path: ^1.9.0
    path_provider: ^2.1.5

    flutter_riverpod: ^2.1.5
    go_router: ^17.0.0
    riverpod_annotation:


    http: ^1.6.0
    uuid: ^4.5.1
    meta: ^1.16.0

    flutter:
      sdk: flutter

    cupertino_icons: ^1.0.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  riverpod_generator:

flutter:
  uses-material-design: true